[workspace]
members = [
    "crates/internal-error",
    "crates/internal-error-derive",
    "xtask",
]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "MIT"
authors = ["Futex"]

[workspace.dependencies]
internal-error = { version = "0.1.0", path = "crates/internal-error" }
internal-error-derive = { version = "0.1.0", path = "crates/internal-error-derive" }
